############################
## CHANGE THESE
############################

baseURL: "https://KamilPietrzak.github.io/KamilPietrzak-blog"
title: 'Kamil "Moneta" Pietrzak'

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "pl"
enableRobotsTXT: true
