############################
## CHANGE THESE
############################

baseURL: "https://KamilPietrzak.github.io/KamilPietrzak-blog"
title: KamilPietrzak-blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
