baseURL: "https://KamilPietrzak.github.io/"
title: 'Kamil "Moneta" Pietrzak'

############################
## MISC
############################

enableEmoji: true
languageCode: "pl"
enableRobotsTXT: true

############################
## TAXONOMIES
############################

taxonomies:
  tag: tags
  author: authors

############################
## RSS CONFIG
############################

outputs:
  home: 
    - HTML
    - RSS
  page:
    - HTML

outputFormats:
  RSS:
    mediaType: "application/rss+xml"
    baseName: "index"
    rel: "alternate"

services:
  rss:
    limit: 20