############################
## Navbar
############################

main:
- name: Blog
  url: /blog/
  weight: 10
- name: O mnie
  url: /about/
  weight: 20
- name: Kontakt
  url: /contact/
  weight: 30