############################
## Navbar
############################

main:
- name: Blog
  url: /blog/
  weight: 10
- name: Tagi
  url: /tags/
  weight: 15
- name: O mnie
  url: /about/
  weight: 20
- name: Kontakt
  url: /contact/
  weight: 30
- name: RSS
  url: /index.xml
  weight: 40